### ISSUE TITLE
Toggle Function Keys is not allowed assistive access

### ISSUE THREAD

**Issue by felipekunzler** [MrSimonC/Toggle-Mac-Function-Keys#16]
Getting the following error even after adding the app to the accessibility list under Privacy & Security and restarting the laptop.
Script runs fine using Script Editor.
Wondering if that's just me.

<img width="251" alt="image" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/9336586/b0062327-dc1b-4998-87b3-766410e71868">

![image](https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/9336586/539fb810-c709-4ee9-a2ac-b63056bb6412)

**Comment by cartesian-plane** [comment]
I have this issue too.
I don't think this is related to the script itself, as I've seen similar stuff when looking into how to fix it.
In the end, I assumed it was just a macOS bug and gave up, though.

**Comment by MrSimonC** [comment]
Thanks for raising the issue. Quickest update is that I can confirm the problem you're having. 🤔 You are right, it's not you it's macOS. I've even done a reboot and it makes no difference… (reference for historical reasons: macOS. Sonoma, 14.3 (23D56)).
 I have had this issue before, so let me have a play around and work on it…

**Comment by MrSimonC** [comment]
Solved!
There is a bug in the way that macOS and Script Editor work together.

Rather than using the File > Save (or Save As) menu, instead we need to use the File > Export menu and tick and select `CodeSign: SignToRunLocally`. See the image below:

This **won't** work:
<img width="710" alt="Screenshot 2024-02-07 at 23 46 28" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/7408f80b-05f6-4dec-ba0e-092c79435072">

Instead, we must do this:
<img width="709" alt="Screenshot 2024-02-07 at 23 47 45" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/f3c7ff29-8823-4d5a-b159-f9904e544caa">

which presents the usual first permission request:
<img width="487" alt="Screenshot 2024-02-07 at 23 48 09" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/cff13734-3698-4931-b6ad-b4f865c432ea">

Put upon running the application, we now get this necessary second request:
<img width="272" alt="Screenshot 2024-02-07 at 23 49 09" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/14a3b7a7-c422-442f-a3bd-ecfa8b75ec05">

This second request places a new entry in the Privacy & Security > Automation menu and then allows system events to be selected in the automation menu, which makes all the difference.

… It's late in my time zone right now, but I'll update the documentation on the main page soon about this.

**Comment by magnanimous123** [comment]
this isn't working for me :( I can't get the second request to pop up - any idea how to fix this?

**Comment by MrSimonC** [comment]
@magnanimous123 if you want to try doing the file export method above, but instead export to your desktop rather than directly to the Applications folder. Try running it then from the desktop. Hopefully you will get both messages if you follow the above screenshots - if it works, then move finally to the Applications folder. Try and let me know how you get on…

**Comment by holovicc** [comment]
I could not get it working either... -25211 is what i get still, regardless where i save.

**Comment by bkromrey** [comment]
Likewise, I cannot get the second pop up to appear so that I can allow the Automation when saving the script as an application in the Applications folder. Running Sonoma 14.4.1. The second pop up did appear when I saved the script as an application on my desktop. Thank you for your work on this!

**Comment by MrSimonC** [comment]
Apologies for checking but thanks for being thorough and ensuring it works by the desktop route… Annoying but glad we have a work around at least! I'm gonna close this issue for now.

**Comment by darwinguz** [comment]
in my case, i had to create an empty script, copy the script, and export (following readme) but with a different previous exported name and done
