### ISSUE TITLE
Script opening "Touch Bar Settings" instead of "Keyboard Shortcuts"

### ISSUE THREAD

**Issue by fyfirman** [MrSimonC/Toggle-Mac-Function-Keys#5]
https://user-images.githubusercontent.com/37064641/229309245-79f57ebc-0a20-46ee-b5cb-9ebc5d26c942.mov

As written in the title, the script run and led to "Touch Bar Settings" make the script stopped. It seems the Settings app get updated and has different UI. It's just me or happen to everyone?  I forgot when I last update the OS but here's the current OS information:
![image](https://user-images.githubusercontent.com/37064641/229309395-a63e80e8-dd97-483a-affa-f78b94e8433e.png)

**Comment by MrSimonC** [comment]
Hello – thanks for opening the issue, and for the pull request. I was indeed wondering how people with a dynamic Touch Bar Mac got on with the script – turns out you are the first! I particularly like the use of you posting a video – I need to start doing that when I raise issues too – it makes it really clear to understand!

Pull request may work for you, but unfortunately breaks it for everybody else - I'll see if I can make the script more dynamic… I might need you to try it out when it's ready if that's okay?

**Comment by fyfirman** [comment]
Ofc, just tell me. 👍🏻

**Comment by MrSimonC** [comment]
So just a General update on this as it's been quite awhile. I've looked into this thoroughly and it is impossible to actually pull the name of the buttons as Apple just doesn't float in the name or description on any of the button meta data fields. I might try and work on looking for the amount of buttons then clicking an appropriate one, but all this is an absolute nightmare in AppleScript as it's not the most forgiving language and comes with no tooling! Let me work on it further now get back to you when I can.

**Comment by MrSimonC** [comment]
Closing for now as I just can't find a way to make this script dynamic to fit this situation since button names just aren't floated to AppleScript.
